# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=200)),
                ('func', models.CharField(max_length=200)),
                ('lines', models.FilePathField(path='/etc/ansible/show/textfiles')),
            ],
        ),
    ]
